name: publish

on:
  push:
    tags: ['v*']

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install dependencies
      run: bundle install --retry=3
    - name: Run tests
      run: bundle exec rspec spec/
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
