name: test

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: [$default-branch]

jobs:
  # This test is used to ensure the chef-solo version of ruby (2.5.0)
  # is able to install miaws successfully.
  test0:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Install dependencies
      run: bundle install --retry=3

    - name: Run tests
      run: bundle exec rspec spec/

  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install dependencies
      run: bundle install --retry=3

    - name: Run tests
      run: bundle exec rspec spec/

    - name: Publish to RubyGems
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
